### ISSUE TITLE
Некорректная работа с отрицательными значениями RingAverage.h

### ISSUE THREAD

**Issue by Laxilef** [GyverLibs/GyverFilters#4]
Приветствую.
При работе с отрицательными значениями (например, температурой), значения на выходе некорректные. Пример измерений:
```
[DS18B20] Raw temp: -3.687500 
[DS18B20] Raw temp: -3.687500 
[DS18B20] Raw temp: -3.687500 
[DS18B20] Raw temp: -3.687500 
[DS18B20] Raw temp: -3.687500 
[DS18B20] Raw temp: -3.750000 
[DS18B20] Raw temp: -3.750000 
[DS18B20] Raw temp: -3.687500 
[DS18B20] Raw temp: -3.750000 
[DS18B20] Raw temp: -3.687500 
[DS18B20] Raw temp: -3.750000 
[DS18B20] Raw temp: -3.750000 
[DS18B20] Raw temp: -3.750000 
[DS18B20] Raw temp: -3.750000 
[DS18B20] Raw temp: -3.750000 
[DS18B20] Raw temp: -3.750000 
[DS18B20] Raw temp: -3.750000 
[DS18B20] Raw temp: -3.750000 
[DS18B20] Raw temp: -3.750000 
[DS18B20] Raw temp: -3.750000 
[DS18B20] Raw temp: -3.750000 
[DS18B20] Raw temp: -3.750000 
[DS18B20] Raw temp: -3.750000 
[DS18B20] Raw temp: -3.750000 
[DS18B20] Raw temp: -3.812500 
[DS18B20] Filtered temp: -3.812500 
[DS18B20] Raw temp: -3.750000 
[DS18B20] Raw temp: -3.750000 
[DS18B20] Raw temp: -3.812500 
[DS18B20] Raw temp: -3.750000 
[DS18B20] Raw temp: -3.750000 
[DS18B20] Raw temp: -3.750000 
[DS18B20] Raw temp: -3.750000 
[DS18B20] Raw temp: -3.812500 
[DS18B20] Raw temp: -3.750000 
[DS18B20] Raw temp: -3.750000 
[DS18B20] Raw temp: -3.812500 
[DS18B20] Raw temp: -3.812500 
[DS18B20] Raw temp: -3.812500 
[DS18B20] Raw temp: -3.812500 
[DS18B20] Raw temp: -3.812500 
[DS18B20] Raw temp: -3.812500 
[DS18B20] Raw temp: -3.812500 
[DS18B20] Raw temp: -3.812500 
[DS18B20] Raw temp: -3.812500 
[DS18B20] Raw temp: -3.812500 
[DS18B20] Raw temp: -3.812500 
[DS18B20] Raw temp: -3.812500 
[DS18B20] Raw temp: -3.812500 
[DS18B20] Raw temp: -3.812500 
[DS18B20] Raw temp: -3.812500 
[DS18B20] Raw temp: -3.812500 
[DS18B20] Raw temp: -3.812500 
[DS18B20] Raw temp: -3.812500 
[DS18B20] Raw temp: -3.812500 
[DS18B20] Raw temp: -3.812500 
[DS18B20] Raw temp: -3.812500 
[DS18B20] Raw temp: -3.812500 
[DS18B20] Raw temp: -3.875000 
[DS18B20] Filtered temp: -3.000000 
[DS18B20] Raw temp: -3.875000 
[DS18B20] Raw temp: -3.875000 
[DS18B20] Raw temp: -3.875000 
[DS18B20] Raw temp: -3.875000 
[DS18B20] Raw temp: -3.875000 
[DS18B20] Raw temp: -3.875000 
[DS18B20] Filtered temp: -2.900000 
[DS18B20] Raw temp: -3.875000 
[DS18B20] Raw temp: -3.875000 
[DS18B20] Raw temp: -3.875000 
[DS18B20] Raw temp: -3.875000 
[DS18B20] Raw temp: -3.812500 
[DS18B20] Raw temp: -3.875000 
[DS18B20] Filtered temp: -2.800000 
[DS18B20] Raw temp: -3.875000 
[DS18B20] Raw temp: -3.875000 
[DS18B20] Raw temp: -3.875000 
[DS18B20] Raw temp: -3.875000 
[DS18B20] Raw temp: -3.875000 
[DS18B20] Raw temp: -3.875000 
[DS18B20] Filtered temp: -2.700000 
[DS18B20] Raw temp: -3.875000 
[DS18B20] Raw temp: -3.875000 
[DS18B20] Raw temp: -3.875000 
[DS18B20] Raw temp: -3.875000 
[DS18B20] Raw temp: -3.937500 
[DS18B20] Raw temp: -3.937500 
[DS18B20] Filtered temp: -2.600000 
[DS18B20] Raw temp: -3.875000 
[DS18B20] Raw temp: -3.875000 
[DS18B20] Raw temp: -3.937500 
[DS18B20] Raw temp: -3.937500 
[DS18B20] Raw temp: -3.937500 
[DS18B20] Raw temp: -3.937500 
[DS18B20] Filtered temp: -2.500000 
[DS18B20] Raw temp: -3.937500 
[DS18B20] Raw temp: -3.937500 
[DS18B20] Raw temp: -3.937500 
[DS18B20] Raw temp: -3.937500 
[DS18B20] Raw temp: -3.937500 
[DS18B20] Raw temp: -3.937500 
[DS18B20] Filtered temp: -2.400000 
[DS18B20] Raw temp: -3.937500 
[DS18B20] Raw temp: -3.937500 
[DS18B20] Raw temp: -3.937500 
[DS18B20] Raw temp: -3.937500 
[DS18B20] Raw temp: -3.937500 
[DS18B20] Raw temp: -3.937500 
[DS18B20] Filtered temp: -2.300000 
[DS18B20] Raw temp: -3.937500 
[DS18B20] Raw temp: -3.937500 
[DS18B20] Raw temp: -3.937500 
[DS18B20] Raw temp: -3.937500 
[DS18B20] Raw temp: -3.937500 
[DS18B20] Raw temp: -3.937500 
[DS18B20] Filtered temp: -2.200000 
[DS18B20] Raw temp: -3.937500 
[DS18B20] Raw temp: -3.937500 
[DS18B20] Raw temp: -3.937500 
[DS18B20] Raw temp: -4.000000 
[DS18B20] Raw temp: -4.000000 
[DS18B20] Raw temp: -4.000000 
[DS18B20] Raw temp: -4.000000 
```

Несмотря на стабильность входных значений (-4 градуса +- 0.3) на выходе с фильтра идет увеличение до -2.2 и увеличивается дальше.

**Comment by GyverLibs** [comment]
однако это оказалась проблема с типом float - сумма хранится в классе как целое число и в итоге начинает стремиться со временем к нулю. Напишу в доке, что для дробных чисел фильтр не работает. Если очень хочется его использовать - нужно заменить `int32_t sum = 0;` на `float sum = 0;` в файле `RingAverage.h`. А вообще для таких целей лучше использовать простейший экспоненциальный фильтр
```cpp
filtered_val += (new_val - filtered_val) * k;
```
где k - 0.001.. 1

**Comment by Laxilef** [comment]
Видимо, тут:
https://github.com/GyverLibs/GyverFilters/blob/56d28411717f2f8795deac31bec658e2dcb6ae5b/src/filters/RingAverage.h#L29
Надо сделать так:
`    TYPE sum = 0;`

PR открывать не буду :) Но можно и пофиксить в сорцах. Тип все равно юзер выбирает сам.

**Comment by GyverLibs** [comment]
нет, так делать нельзя. Тип переменной суммы должен вмещать больше, чем принимаемые данные, иначе сумма зашкалит и фильтр не будет работать

**Comment by Laxilef** [comment]
Так то и int32_t можно переполнить. Корректнее было бы упомянуть, что в указанный тип должна влезать сумма буфера. Либо добавить в шаблон SUM_TYPE. Для float можно использовать double, туда уж точно залезет.

**Comment by GyverLibs** [comment]
> Так то и int32_t можно переполнить

можно, поэтому лучше использовать экспоненциальный фильтр. Все "суммирующие" фильтры нужны для каких то особых целей, когда важна форма графика например. У экспоненциального она отличается и усреднение ведёт себя чуть иначе.

> что в указанный тип должна влезать сумма буфера

не должна, буфер 32 бит по умолчанию

> double, туда уж точно залезет

На AVR такого нету

**Comment by Laxilef** [comment]
Не одним AVR'ом мир живет. М.б. рассмотреть вариант добавить SUM_TYPE? Реально удобнее, чем множить все это на 10к и потом фильтрованное делить.

**Comment by GyverLibs** [comment]
добавить можно

> удобнее, чем множить все это на 10к и потом фильтрованное делить

зачем такая порнография, если есть удобный экспоненциальный фильтр?)

**Comment by Laxilef** [comment]
В моем случае измерения раз в 5 секунд, и размер буфера в 60 измерений дает норм. результат на выходе без танцев с бубном с подбором K для эксп. фильтра :) По крайней мере всплески, в случае попадения на датчик солнца или при сильном обдуве датчика зимой не оч заметны, т.к. полное обновление произойдет через 5 минут. Значения +- стабильны.

При использовании эксп. фильтра нужно подбирать коэф так, чтобы не было затупов при реальном изменении температуры и не было "шума" с датчика при внешнем воздействии (солнце, ветер, цунами, апокалипсис и т.п.)
